Ajout de l'exercice de nombre de jours à une date donnée
ETS-Winter-2024-CUT/INF111-Exemples_Java pull request #10
Opened 2023-12-28 23:37 UTC by Vianpyro

## Description de la Pull Request

### Description brève des modifications

Ajout du fichier `NombreJoursADate.java` contenant un programme Java qui détermine le nombre de jours dans un mois donné pour une année spécifique.

### Détail des modifications

La modification principale consiste en l'ajout de la méthode `nbr_jours_mois` qui prend en compte le mois et l'année pour renvoyer le nombre de jours dans ce mois pour cette année. De plus, la méthode `annee_est_bisextile` a été intégrée pour vérifier si une année est bissextile ou non, ce qui affecte le nombre de jours dans le mois de février.

### Objectif des modifications

Cette Pull Request ajout un programme qui permet de calculer correctement le nombre de jours pour le mois de l'année donné par l'utilisateur.

### Captures d'écran (le cas échéant)

![image](https://github.com/ETS-Winter-2024-CUT/INF111-Exemples_Java/assets/10519369/680d9853-6662-4686-b7b4-7faaf79e8d5a)

### Étapes de vérification

1. Exécuter le programme.
2. Saisir différents mois et années, notamment des années bissextiles.
3. Vérifier que le nombre de jours retourné pour le mois de février correspond correctement aux années bissextiles selon le calendrier grégorien.
4. S'assurer que le programme signale correctement les mois invalides ou les années antérieures à 1582.

### Notes pour le relecteur

- La logique pour vérifier si une année est bissextile est basée sur les règles standard du calendrier Grégorien.
- Assurez-vous que la méthode `nbr_jours_mois` retourne le bon nombre de jours pour chaque mois.
- Veuillez vérifier la lisibilité et la clarté du code ajouté.

2024-01-05 15:09 UTC, AdelnorAcmorux approved these changes

2024-01-08 19:22 UTC, AdelnorAcmorux submitted a review, later dismissed

2024-01-08 20:05 UTC, PabloCoroa submitted a review, later dismissed

2024-01-08 20:16 UTC, MassiveDifference commented on src/NombreJoursADate.java
> +    private static int nbr_jours_mois(int annee, int mois) {
```suggestion
    private  int nbrJoursMois(int annee, int mois) {
```

2024-01-08 20:17 UTC, MassiveDifference requested changes
Il n'est pas necessaire de mettre le tag `static` pour les methodes `annee_est_bisextile` et `nbr_jours_mois` et aussi en java on utilise camelCase

2024-01-08 20:17 UTC, MassiveDifference commented on src/NombreJoursADate.java
> +    private static boolean annee_est_bisextile(int annee) {
```suggestion
    private boolean anneeEstBissextile(int annee) {
```

2024-01-08 20:27 UTC, Vianpyro commented
> Il n'est pas necessaire de mettre le tag `static` pour les methodes `annee_est_bisextile` et `nbr_jours_mois` et aussi en java on utilise camelCase

Si, sinon on obtient cette erreur: `Cannot make a static reference to the non-static method anneeEstBissextile(int) from the type NombreJoursADate`

2024-01-08 20:52 UTC, MassiveDifference approved these changes
LGTM!

2024-01-08 20:54 UTC, AdelnorAcmorux approved these changes

2024-01-08 20:55 UTC, merged