Ajout de l'exercice sur les boucles "for"
ETS-Winter-2024-CUT/INF111-Exemples_Java pull request #11
Opened 2023-12-29 02:02 UTC by Vianpyro

## Description de la Pull Request

### Description brève des modifications

Ajout du fichier `BoucleFor.java` contenant un programme Java pour afficher différents ensembles de nombres en utilisant des boucles `for` et des conditions.

### Détail des modifications

Le fichier `BoucleFor.java` présente un programme Java qui affiche plusieurs ensembles de nombres répondant à des critères spécifiques. Il utilise des boucles `for` pour générer et afficher des nombres impairs entre 1 et 100, des nombres pairs entre 100 et 1, des nombres divisibles par 3 entre 99 et 300, ainsi que des nombres divisibles par 7 entre 700 et 600.

### Objectif des modifications/Problème résolu (le cas échéant)

Cette Pull Request a pour objectif d'ajouter un exemple de programme Java illustrant l'utilisation de boucles `for` pour générer et afficher des ensembles de nombres répondant à des critères spécifiques (impairs, pairs, divisibles par 3, divisibles par 7). L'objectif est de démontrer comment réaliser ces opérations numériques de manière itérative en Java.

### Captures d'écran (le cas échéant)

Pas de capture d'écran pour cette modification.

### Étapes de vérification

1. Examiner le fichier `BoucleFor.java` ajouté.
2. Vérifier que le programme compile sans erreurs.
3. Tester le programme en exécutant chaque ensemble de nombres affichés pour vérifier leur conformité aux critères spécifiés.
4. S'assurer que les boucles `for` génèrent les ensembles de nombres corrects selon les critères définis.

### Notes pour le relecteur

- Veuillez vérifier la conformité aux bonnes pratiques de codage Java.
- Assurez-vous que le programme génère correctement les ensembles de nombres spécifiés (impairs, pairs, divisibles par 3, divisibles par 7) selon les boucles `for` et les conditions définies.
- Toute suggestion d'amélioration ou de clarification du code est la bienvenue.

2024-01-05 15:09 UTC, AdelnorAcmorux approved these changes

2024-01-05 15:21 UTC, PabloCoroa approved these changes

2024-01-08 17:46 UTC, AdelnorAcmorux approved these changes, later dismissed

2024-01-08 19:03 UTC, PabloCoroa approved these changes, later dismissed
bon travail

2024-01-08 19:44 UTC, AdelnorAcmorux submitted a review, later dismissed
©

2024-01-08 20:05 UTC, MassiveDifference commented on src/BoucleFor.java
> +        for (int i = 1; i <= 100; i++) {
```suggestion

        for (int i = 1; i <= 100; i++) {
```

2024-01-08 20:07 UTC, MassiveDifference commented on src/BoucleFor.java
> +        System.out.println("\n");
```suggestion
        System.out.println();
```

2024-01-08 20:09 UTC, MassiveDifference requested changes
Eviter les chiffres magiques aussi. Ca sert a rien ici mais pour le futur c'est bon.

2024-01-08 20:12 UTC, PabloCoroa submitted a review, later dismissed

2024-01-08 20:51 UTC, MassiveDifference approved these changes
LGTM

2024-01-08 20:54 UTC, AdelnorAcmorux approved these changes

2024-01-08 20:54 UTC, merged