ajoue des premiers docs
ETS-Winter-2024-CUT/INF111-Exemples_Java pull request #15
Opened 2024-01-02 18:41 UTC by AdelnorAcmorux

2024-01-02 20:20 UTC, Vianpyro commented
Il manque la description, les reviewers, l'assignation, les labels et il faut que tous les fichiers soient dans le dossier "`src`"

2024-01-02 21:42 UTC, Vianpyro requested changes
- [ ] Il manque la description.
- [ ] Il manque les reviewers.
- [ ] Il manque l'assignation.
- [ ] Il manque les labels.
- [ ] Il faut que tous les fichiers Java soient dans le dossier "`src`".
- [ ] Par convention on ajoute des espaces autour des opérateurs.
- [ ] Le nom de la branche ne respecte par les normes (devrait commencer par `feature/`, ne pas contenir de majuscule ni de caractères spéciaux)

2024-01-05 12:49 UTC, Vianpyro requested changes
Voici quelques changements que je te propose de faire pour améliorer la lisibilité 🦄

2024-01-05 12:49 UTC, Vianpyro commented on GUI_intro.java
> +        JOptionPane.showMessageDialog(null, "Hello "+name);
```suggestion
        JOptionPane.showMessageDialog(null, "Hello " + name);
```
C'est plus sympa d'aérer un peu autours des opérateurs ^^

2024-01-05 12:49 UTC, Vianpyro commented on GUI_intro.java
> +        JOptionPane.showMessageDialog(null, "Your are "+age+" years old");
```suggestion
        JOptionPane.showMessageDialog(null, "Your are " + age + " years old");
```

2024-01-05 12:49 UTC, Vianpyro commented on GUI_intro.java
> +        JOptionPane.showMessageDialog(null, "Your are "+height+" meters tall");
```suggestion
        JOptionPane.showMessageDialog(null, "Your are " + height + " meters tall");
```

2024-01-05 12:49 UTC, Vianpyro commented on random_numbers.java
> +        int x = random.nextInt(6)+1;
```suggestion
        int x = random.nextInt(6) + 1;
```

2024-01-05 12:49 UTC, Vianpyro commented on user_input.java
> +        System.out.println("What is your name? ");
```suggestion
        System.out.println("What is your name?");
```
Tu peux enlever l'espace à la fin puisque `println` va ajouter un saut de ligne à la fin du print.

2024-01-05 12:49 UTC, Vianpyro commented on user_input.java
> +        System.out.println("How old are you ");
```suggestion
        System.out.println("How old are you?");
```

2024-01-05 12:49 UTC, Vianpyro commented on user_input.java
> +        System.out.println("What is your favorite food? ");
```suggestion
        System.out.println("What is your favorite food?");
```

2024-01-05 12:49 UTC, Vianpyro commented on user_input.java
> +        System.out.println("Hello "+name);
```suggestion
        System.out.println("Hello " + name);
```

2024-01-05 12:49 UTC, Vianpyro commented on user_input.java
> +        System.out.println("Your favorite food is "+food);
```suggestion
        System.out.println("Your favorite food is " + food);
```

2024-01-05 12:49 UTC, Vianpyro commented on user_input.java
> +        System.out.println("You are "+age+" years old");
```suggestion
        System.out.println("You are " + age + " years old");
```

2024-01-05 12:49 UTC, Vianpyro commented on variables.java
> +            System.out.println("Hello "+name);
```suggestion
            System.out.println("Hello " + name); 
```

2024-01-05 12:49 UTC, Vianpyro commented on variables.java
> +             */
```suggestion
             */

```

2024-01-05 15:23 UTC, PabloCoroa submitted a review, later dismissed

2024-01-06 03:28 UTC, Vianpyro requested changes
Il y'a encore quelques modifications mineures à apporter

2024-01-06 03:28 UTC, Vianpyro commented on src/user_input.java
> +        scanner1.nextLine();
```suggestion
        scanner1.nextLine();
                
        scanner1.close()
```
⚠️ Attention à fermer le scanner une fois la saisie terminée! ⚠️

2024-01-06 03:28 UTC, Vianpyro commented on src/variables.java
> +            int x = 123;
```suggestion
```
Variable inutilisée

2024-01-06 03:28 UTC, Vianpyro commented on src/variables.java
> +            double y = 3.14;
```suggestion
```
Variable inutilisée

2024-01-06 03:28 UTC, Vianpyro commented on src/variables.java
> +            boolean z = true;
```suggestion
```
Variable inutilisée

2024-01-08 14:52 UTC, AdelnorAcmorux commented on src/variables.java
> +            boolean z = true;
C'est juste un exemple, on garde comme ca.

2024-01-08 17:48 UTC, Vianpyro approved these changes
First try! 👌

2024-01-08 19:05 UTC, PabloCoroa approved these changes

2024-01-08 19:05 UTC, merged